general:
  server: 192.168.1.100
probe:
  probe_name: probe01
  probe_description: this probe scans Cordoba user applications
  location:
    area: TIC
    building: HURS
    city: Córdoba
    floor: Semisotano
    room: CPD
  actions:
  - action_name: afetch
    action_description: aiohttp fetch
    action_id: 1
    items:
      - 'http://www.elpais.es'
      - 'http://www.ideal.es'
    iterations: .inf
    period: 1
    version: 0.1
  - action_name: aping
    action_description: aping
    action_id: 1
    items:
      - 'www.google.es'
      - 'www.elpais.es'
    iterations: 3
    period: 1
    version: 0.1