general:
  server: 192.168.1.100
probe:
  probe_name: probe01
  probe_description: this probe scans Cordoba user applications
  location:
    area: TIC
    building: HURS
    city: Córdoba
    floor: Semisotano
    room: CPD
  actions:
  - action_name: async_sleep
    action_description: asyncronous sleep method (asyncio)
    action_id: 1
    periodicity: 1
    version: 0.1
  - action_name: get_url
    action_description: aiohttp fetch
    action_id: 1
    periodicity: 1
    version: 0.1